package view;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import model.Slideshow;

/**
 * Сова
 */
public class AddMusicDialog extends javax.swing.JFrame {

    MainGUI parent;
    
    public AddMusicDialog(MainGUI parent) {
        initComponents();
        this.parent = parent;        
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathField = new javax.swing.JTextField();
        chooseFile = new javax.swing.JButton();
        startingField = new javax.swing.JTextField();
        startsTipLabel = new javax.swing.JLabel();
        fileTipLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        canselButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pathField.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        pathField.setForeground(new java.awt.Color(204, 204, 204));
        pathField.setText("/путь_к_файлу../music.ogg");

        chooseFile.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        chooseFile.setText("Выбрать..");
        chooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileActionPerformed(evt);
            }
        });

        startingField.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        startsTipLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        startsTipLabel.setForeground(new java.awt.Color(153, 153, 153));
        startsTipLabel.setText("Начало дорожки (тик FPS):");

        fileTipLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        fileTipLabel.setForeground(new java.awt.Color(153, 153, 153));
        fileTipLabel.setText("Путь к файлу:");

        okButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        okButton.setText("Ок");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        canselButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        canselButton.setText("Отмена");
        canselButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canselButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileTipLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(startsTipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pathField)
                            .addComponent(okButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chooseFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startingField)
                            .addComponent(canselButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(fileTipLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startingField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startsTipLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(canselButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileActionPerformed
        JFileChooser fc = new JFileChooser();
        int result = fc.showOpenDialog(this);
            //TODO: создать фильтры FileChooser для того, чтобы нельзя было выбрать неподдерживаемый формат   
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                String sound = fc.getSelectedFile().getCanonicalPath();
                pathField.setText(sound);
                pathField.setForeground(Color.black);
                this.repaint();
            } catch (IOException ex) {
                Logger.getLogger(AddMusicDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_chooseFileActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        //TODO: сделать валидацию на буквы и спецсимволы в циферном поле
        int starts = Integer.parseInt(startingField.getText());
        //TODO: сделать валидацию пути к файлу
        String path = pathField.getText();
        parent.processNewMusic(parent.slideshow.new Music(starts, path));
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void canselButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canselButtonActionPerformed
        this.dispose(); 
    }//GEN-LAST:event_canselButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canselButton;
    private javax.swing.JButton chooseFile;
    private javax.swing.JLabel fileTipLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField pathField;
    private javax.swing.JTextField startingField;
    private javax.swing.JLabel startsTipLabel;
    // End of variables declaration//GEN-END:variables
}
